### ISSUE TITLE
NameError: name 'gpiod_line' is not defined 

### ISSUE THREAD

**Issue by GASH-05** [ibin-study/RT_test_by_hx711#1]
Hi ibin-study,
while "import gpiod" getting error as "NameError: name 'gpiod_line' is not defined ".
Can you please help me interface HX711 with jetson nano.
I am really struggling hard. 
Please help.

**Comment by ibin-study** [comment]
Hi, @GASH-05 . I don't think such error occurred when I did. Can you upload it with the error log?
If you're using Python 2.x version, maybe it's a difference from there.

**Comment by GASH-05** [comment]
@ibin-study ,
import gpiod
  File "/home/nvidia/.local/lib/python3.6/site-packages/gpiod/__init__.py", line 24, in <module>
    from . import libgpiodcxx
  File "/home/nvidia/.local/lib/python3.6/site-packages/gpiod/libgpiodcxx/__init__.py", line 33, in <module>
    from .. import libgpiod
  File "/home/nvidia/.local/lib/python3.6/site-packages/gpiod/libgpiod/__init__.py", line 41, in <module>
    from .gpiod_h import *
  File "/home/nvidia/.local/lib/python3.6/site-packages/gpiod/libgpiod/gpiod_h.py", line 41, in <module>
    class gpiod_line_bulk:
  File "/home/nvidia/.local/lib/python3.6/site-packages/gpiod/libgpiod/gpiod_h.py", line 49, in gpiod_line_bulk
    def add(self, line: gpiod_line) -> None:
NameError: name 'gpiod_line' is not defined

**Comment by GASH-05** [comment]
@ibin-study ,
I followed the document https://github.com/kempei/hx711py-jetsonnano for installation as it is. while Running example.py file from the repo i am getting the above error

**Comment by GASH-05** [comment]
@ibin-study ,

Can you help me with installation steps if  i am missing on something

**Comment by ibin-study** [comment]
@GASH-05 , I think it might not be installed well... How about delete gpiod directory and reinstall it step by step again??

**Comment by GASH-05** [comment]
@ibin-study , 
Now i am able to run the example.py successfully by installing hx711-jetsonnano on python virtual environment.
But i am concerned about, i want to run the code without using python virtual environment.
Any suggestions will be helpful. thank you @ibin-study

**Comment by ibin-study** [comment]
@GASH-05 ,
when I used  [https://github.com/kempei/hx711py-jetsonnano](https://github.com/kempei/hx711py-jetsonnano) repository at first, I also met some error while running example.py.  (But, I think my errors are not  same with your case.)
So , I modified some code in hx711.py (I didn't modify gpiod library). You can find my code at this repo or [https://github.com/ibin-study/hx711py-jetsonnano](https://github.com/ibin-study/hx711py-jetsonnano).
If you already reinstalled gpiod library and didn't resolve, how about using my repo which i modified from kempei's code?

I test my code now, example.py can run correctly. 
I hope this advice can help you.
